server:
  port: 8085

#spring.data.mongodb.uri=mongodb+srv://user:pass@trainer-qi6hz.mongodb.net/test?retryWrites=true
  #spring.data.mongodb.database=auto-trainer
spring:
  data:
    mongodb:
      uri: mongodb+srv://webflux:webflux123@cluster0-xad87.mongodb.net/test?retryWrites=true&w=majority
  application:
    name: webflux-server
  profiles:
    active: dev
  cloud:
    kubernetes:
      enabled: false
---
spring:
  profiles: dev
---
spring:
  profiles: nonprod
---
spring:
  profiles: prod
