spring:
  application:
    name: webflux-server
  profiles:
    active: dev
  sleuth:
    async:
      enabled: false
server:
  port: 8085
---
spring:
  profiles: dev
---
spring:
  profiles: nonprod
---
spring:
  profiles: prod
